name: unit-testing backend
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: npm run test -- --json --outputFile=${{ github.workspace }}/backend/src/tests/results/output-${{ github.run_id }}-${{ github.run_attempt }}.json

    - run: |
        echo 'RESULT_TEST<<EOF' >> $GITHUB_ENV
        cat ${{ github.workspace }}/backend/src/tests/results/output-${{ github.run_id }}-${{ github.run_attempt }}.json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          ${{ fromJson(env.RESULT_TEST) }}
        reactions: eyes