name: unit-testing backend
on: push
jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: npm run test -- --json --outputFile="./output-${{ github.run_id }}-${{ github.run_attempt }}.json"

    - run: |
        echo 'RESULT_TEST<<EOF' >> $GITHUB_ENV
        cat ./output-${{ github.run_id }}-${{ github.run_attempt }}.json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    -run: echo ${{ fromJson(env.RESULT_TEST) }}

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          ###Tests results###
          ```json
            ${{ fromJson(env.RESULT_TEST) }}
          ```